[package]
name = "fighting_daisy"
version = "0.2.0"
edition = "2024"
authors = ["Silen Locatelli", "LunchTime Code"]
license = "MIT"
description = "Library for fighting daisies"


[dependencies]
maud = "0.27.0"
include_directory = "0.1.1"
derive_builder = "0.20.2"
